config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#sign_in'
  resources :sessions, only: [:sign_in, :create, :destroy]
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  #get '/auth/facebook/callback', to: 'sessions#create'
  #get '/auth/github/callback', to: 'sessions#create'
  

  resources :students, only: [:index, :new, :create]

  resources :lists

  resources :courses, only: [:index, :show, :new, :create]

  resources :students, only: [:show] do 
    resources :lists
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/class.rb
class Class < ApplicationRecord
  belongs_to :professor
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :lists
  has_many :students, through: :lists

  validates :name, presence: true

  def self.search(search)
    if search 
      course = Course.find_by(name: search)
      if course
        self.where(name: course.name)
      else
        Course.all
      end
    else
      Course.all
    end
  end
  
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :student
  belongs_to :course

end

app/models/student.rb
class Student < ApplicationRecord
  has_many :lists
  has_many :courses, through: :lists

  has_secure_password

  validates :name, :major, :email, :password, presence: true 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  private

  def current_user
    session[:user_id]
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  def index
    @courses = Course.search(params[:search])
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.valid?
      @course.save
      redirect_to course_path(@course)
    else
      flash[:notice] = "Something went wrong. Make sure the name field is filled out."
      render :new
    end
  end

  private

  def course_params
    params.require(:course).permit(:name, :description, :search)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
  end

  def new 
    @list = List.new
    @student = current_user
  end

  def create
    if list_params
      list_params[:course_id].each do |course_id|
        if course_id != ""
          List.find_or_create_by(student_id: current_user, course_id: course_id)
        end
      end
      redirect_to student_path(current_user)
    else
      flash[:notice] = "Something went wrong. Make sure you have selected at least 1 class before submitting."
      redirect_to new_student_list_path(current_user)
    end
  end

=begin
  def edit
    @lists = List.where(student_id: current_user)
    byebug
  end

  def update
    if list_params
      list_params[:course_id].each do |course_id|
        if course_id != ""
          List.update(student_id: current_user, course_id: course_id)
        end
      end
      redirect_to student_path(current_user)
    else
      flash[:notice] = "Something went wrong. Make sure you have selected at least 1 class before submitting."
      redirect_to new_student_list_path(current_user)
    end
  end
=end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to student_path(current_user)
  end

  private

  def list_params
    params.require(:list).permit(:student_id, course_id: [])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def sign_in 
  end

  def create

    @student = Student.find_or_create_by(email: params[:email])

    return head(:forbidden) unless @student && @student.authenticate(params[:password])
    session[:user_id] = @student.id 
    redirect_to student_path(@student)
  end

  def destroy
    current_user = nil
    redirect_to root_path
  end

  private

  def auth 
    request.env['omniauth.auth']
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.create(student_params)

    if @student.valid?
      @student.save
      session[:user_id] = @student.id 
      redirect_to student_path(@student)
    else
      flash[:notice] = "Make sure you have all fields filled out. If you have not decided a major, put undecided."
      redirect_to new_student_path
    end

  end

  private

  def student_params
    params.require(:student).permit(:name, :major, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  #def previous_url
    #URI(request.referer || '').path
  #end

end

app/helpers/list_helper.rb
module ListHelper 
end

app/helpers/student_helper.rb
module StudentHelper
=begin
  def student_courses(student)
    courses = []
    student.list.course_id.split(/\W/).each do |id|
      if id != ""
        course = Course.find_by(id: id)
        courses.push(course)
      end
    end
    courses
  end
=end
end

app/views/courses/index.html.erb
<div id="courses-container">
  <div id="nav-btns">
    <button class="link-btn"><%= link_to "Back to previous page", :back %></button>
    <button class="link-btn"><%= link_to "Back to Home", student_path(session[:user_id]) %></button>
  </div>
  <h2>Looking for a Specific Class?</h2>
  <p>Search here</p>

  <div>
    <%= form_tag(courses_path, method: :get) do %>
      <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag("Search") %>
    <% end %>
  </div>

  <ul>
    <% @courses.sort_by{|course| course.name }.each do |course| %>
      <li><%= link_to course.name, course_path(course), :class => 'course-link' %></li><br>
    <% end %>
  </ul>
</div>

app/views/courses/new.html.erb
<%= link_to "Cancel", student_path(session[:user_id]), :class => 'log-out-btn' %><br>
<div class="new-course-container">
  <h2>Create New Course</h2>
  <%= render partial: "layouts/error" %>
  <%= form_for(@course) do |f| %>
    <%= f.label "Course Name and Number" %><br>
    <%= f.text_field :name %><br>
    <%= f.label "Course Description - optional" %><br>
    <%= f.text_area :description, size: "35x10" %><br>
    <%= f.submit "Submit New Course" %>
  <% end %>
</div>

app/views/courses/show.html.erb
<div id="course-show-container">
  <h2>More Info about <%= @course.name %></h2>
  <h4>Description</h4>
  <p><%= @course.description %></p>
</div>
<button class="link-btn"><%= link_to "Back to previous page", :back %></button>
<button class="link-btn"><%= link_to "Back to Home", student_path(session[:user_id]) %></button>

app/views/layouts/_error.html.erb
<% flash.each do |type, msg| %>
  <div class="error-message">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsClassLister</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main-app-header">
      <h2>ClassLister</h2>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div id="lists-partial-container">
  <h3 id="list-header">Choose Classes</h3><br> 
  <%= form_for(@list) do |f| %>
    <%= f.hidden_field :student_id, value: @student %>
    <%= f.collection_check_boxes(:course_id, Course.all, :id, :name) do |b| %>
    <%= b.check_box %> - <%= b.label %><br>
    <% end %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/edit.html.erb
<%= link_to "Cancel", student_path(session[:user_id]), :class => 'log-out-btn' %><br>
<h2 id="list-form-header">Edit Your Current Classes</h2>
<%= render partial: "layouts/error"%>
<%= link_to "Search by Class Name", courses_path, :class => 'search-class-link' %>
<div id="lists-partial-container">
  <h3 id="list-header">Choose Classes</h3><br> 
  <%= form_for(@lists) do |f| %>
    <%= f.hidden_field :student_id, value: @student %>
    <%= f.collection_check_boxes :course_id, Course.all, :id, :name %>
    <%= f.submit %>
  <% end %>
</div>
<div class="new-course-container">
  <h4>Don't see the course you're looking for?</h4>
  <%= link_to "Share a New Course", new_course_path %>
</div>

app/views/lists/new.html.erb
<%= link_to "Cancel", student_path(session[:user_id]), :class => 'log-out-btn' %><br>
<h2 id="list-form-header">New Class List</h2>
<%= render partial: "layouts/error" %>
<%= link_to "Search by Class Name", courses_path, :class => 'search-class-link' %>
<%= render 'form' %>
<div class="new-course-container">
  <h4>Don't see the course you're looking for?</h4>
  <%= link_to "Share a New Course", new_course_path %>
</div>

app/views/students/index.html.erb
<ul>
  <% @students.each do |student| %>
    <li><%= student.name %> - <%= student.major %></li>
  <% end %>
</ul>

app/views/students/new.html.erb
<div id="form-container">
  <h2 id="form-header">Create Your New Class Lister Account</h2>
  <%= render partial: "layouts/error"%>
  <div id="sign-up-form">
    <%= form_for(@student) do |f| %>
      <%= f.label :name, "Full Name" %><br>
      <%= f.text_field :name %><br>
      <%= f.label :major, "What is your Major?" %><br>
      <%= f.text_field :major %><br>
      <%= f.label :email, "School Email" %><br>
      <%= f.text_field :email %><br>
      <%= f.label :password, "Create Password" %><br>
      <%= f.password_field :password %><br>
      <%= f.label :password_confirmation, "Confirm Password" %><br>
      <%= f.password_field :password_confirmation %><br>
      <%= f.submit "Submit" %>
    <% end %>
    <%= link_to "Cancel", root_path, :class => 'cancel-btn' %>
  </div>
</div>

app/views/students/show.html.erb
<% if session[:user_id] %>
  <%= link_to "Log Out", session_path(@student), method: :delete, :class => 'log-out-btn' %>
  <h2 id="student-show-header">Welcome, <%= @student.name %></h2>
  <% if @student.courses.empty? %>
    <h4 id="student-show-header">It does not appear that you have any scheduled classes</h4>
    <div class="link-btns-container">
      <%= link_to "Create a Class List", new_student_list_path(@student), :class => "link-btn" %>
    </div>
  <% else %>
    <h4 id="student-show-header">Your Class List</h4>
    <div id="student-class-list-container">
    <ul id="student-class-list">
    <% @student.lists.each do |list| %>
      <li><%= link_to list.course.name, course_path(list.course.id) %> ---- <%= link_to "Drop Course", student_list_path(@student, list), method: :delete, data: { confirm: 'Are you sure you would like to delete your current class list?' } %></li>
    <% end %>
    </ul>
    <div id="link-btns-container">
      <%= link_to "Add Class to List", new_student_list_path(@student), :class => "link-btn" %>
    </div>
  <% end %>
<% end %>